### ISSUE TITLE
datacats start occasionaly misreports "already running"

### ISSUE THREAD

**Issue by deniszgonjanin** [boxkite/datacats#21]
Occasionally, due to boot2docker weirdness or other problems, `datacats start` will report that the project is already running, but it is not. Suspect because containers were merely stopped by a boot2docker vm shutting down.

`start` should check whether the containers are halted or not

`datacats info` output:
```    
Project name: ottawa
    CKAN version: master
    Default port: 5698
     Project dir: /Users/dz/source/dcats-envs/ottawa
        Data dir: /Users/dz/.datacats/ottawa
      Containers: web(halted) data(halted) search(halted)
    Available at: http://boot2docker:5698/
```

**Comment by wardi** [comment]
fixed by #53
