### ISSUE TITLE
Can not deploy

### ISSUE THREAD

**Issue by amercader** [boxkite/datacats#67]
* Run `datacats deploy`:

![screenshot from 2015-04-20 15 53 02](https://cloud.githubusercontent.com/assets/200230/7232817/96ef6364-e775-11e4-96fe-953fa783f2d1.png)

* Went to http://www.datacats.com/account/key (not https as it is not working):

![okd2qhz](https://cloud.githubusercontent.com/assets/200230/7232843/b65f808a-e775-11e4-872e-7b908911163d.png)

* Tried again:

```
datacats deploy
["unauthorized to update", "testrtl"]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]
```

Is there a way that I can view / recreate my local pub key?

**Comment by deniszgonjanin** [comment]
First, can you try:
```
datacats deploy --create
```
to make sure the environment gets created. 

If that doesn't work, it could be that copying public keys is a bit finicky. Try:
```
pbcopy < ~/.datacats/user-profile/id_rsa.pub
```

That should copy the key to the clipboard, then just paste that to http://www.datacats.com/account/key

If that also doesn't work, let me know here and I'll look into it further

**Comment by amercader** [comment]
Thanks, `datacats deploy --create` worked and subsequent calls to `datacats deploy` as well, so I guess it is an issue with trying to update an env that is not there.

Is this command supposed to sync my local database as well? eg datasets that I've created locally. The output says `Updating DB` but datasets don't seem to come up on the cloud instance.

Would be nice if the output of `datacats deploy` showed the url of your site as well, like `create`.

**Comment by wardi** [comment]
I completely agree about showing the URL.

For migrating data the only option is to use the API. I think that's the best method, adding something special feels wrong to me. `ckanapi dump datasets | ckanapi load datasets` is nice, copying orgs has some issues we should fix anyway on the ckanapi side. I don't know about migrating users, but I think that should be fixed in core ckan too so that users can be migrated via api.

**Comment by wardi** [comment]
Now printing the URL on deploy: b3cddf6 I'll wait until we support deploying to other places before making this code more complicated.
